### ISSUE TITLE
[Feature Request] ‘Exolve feature’ editing – for Preamble, Questions, Ninas, Colours, etc.

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exet#12]
I'm sure you will have already given this some thought, but I wondered whether you had any plans as yet to provide editing of such Exolve features within Exet?

**Comment by viresh-ratnakar** [comment]
I have been contemplating doing this and have some thoughts. This is a good opportunity to write them out and discuss before implementing.

- For my own crosswords, I have been saving the Exolve file and manually editing it to add preamble/explanations/ninas. After editing manually, I reload it into Exet, which already does the basic nice things that you'd expect: continues the edit history of the same crossword as the ID is the same, renders the added sections/features, and preserves them with subsequent Saves.  
- For the preamble/explanations section, for reasons that I've previously covered, I will not be adding a full WYSIWYG editor.
- What I have in mind is that from the Edit menu you will have options to add/edit Preamble/Explanations/Questions/Ninas/Colours
- For Preamble/Explanations, you will simply get a panel in which you can add/edit raw HTML, and no formatting buttons.
- For Questions, I can make it a little smarter, giving options to provide the enum, and whether it should be hidden, and whether lowercase letters are accepted (mapping to Exolve features for these options), and to reorder the questions. I can also add a way to provide the Submit URL if desired.
- For ninas/colours: I think of these as higher priority than the above, actually, because the above sections are all easily edited directly in the Exolve file, whereas ninas/colorus are a bit painful as you have to spell out their chessboard-notation locations. A UI where you can toggle a cell's inclusion in a specific exolve-nina/exolve-colour group by clicking on the cell will be convenient.
  - I also want "clear this" and "clear all" in Exet to not delete letters that are parts of some nina. I almost always include ninas in my grids, and this is the part that is annoying when doing the grid fill.

**Comment by Antagony1060** [comment]
Thanks! That all makes sense. I work pretty much the same way you do, although I also occasionally publish other redditors' puzzles so the more they can do in Exet, the less I will need to do with their widget code and that at least gives me the opportunity to try solving them too, if I want to.

I agree that Ninas and colours should be the highest priority as they can be a chore to enter manually. I initially just envisioned a simple mode toggle to paint the cells with when on, but I see now that of course it needs a mechanism to add/remove items. One thing that's just occurred to me is that it might be worth having a bit of rethink on how Ninas work in Exolve, to allow setters to pick their own colours. In essence that would/could make Ninas and colours identical, Exet usage-wise, except for a ‘Nina’ flag. Just a thought…

I hadn't considered formatting for the various text editing fields, but now you've mentioned it I think it would be a nice addition at some point in the future maybe. Simple italic/bold/strikethrough formatting should be sufficient in most cases, so couldn't you functionalise/re-use what you've written for anno editing? Of course it would also need a preview pane or similar if it's just adding raw HTML tags to the text.

**Comment by viresh-ratnakar** [comment]
I have added editing preamble/explanations/questions/ninas/colours to Exet now, with v0.39. You can access these controls with the (reorganized) Edit menu, and with keyboard shortcuts for ninas/colours.

The new features are described here: https://github.com/viresh-ratnakar/exet#supported-crossword-features

**Comment by Antagony1060** [comment]
I haven't tested it thoroughly as yet, but so far everything seems logical and works as I hoped/expected. Great work as usual… many thanks!
