### ISSUE TITLE
Toggle symmetry globally

### ISSUE THREAD

**Issue by jdacre** [viresh-ratnakar/exet#18]
Dear Viresh,

You have made an exquisite tool and I am loving it! One small recommendation I would make is to include an option to toggle symmetry on/off globally, rather than just for next cell changed, as I desire to make some grids with reflectional symmetry but no rotational symmetry - and perhaps some with little symmetry of any kind. If this doesn't affect other functionality, I feel this might be a very useful option.

Kind regards,

Josh - a new and impressed user

**Comment by viresh-ratnakar** [comment]
I've made this change with v0.65 now:

- Make the "Do not force symmetry" option sticky. Previously, it applied
  to just the next bar/block change. If someone's likely to break symmetry,
  they are likely to do that across a puzzle rather than just at a few cells,
  so for them the old way was painful. Make this option stick with the specific
  crossword (so that for a new crossword we default to enforcing symmetry).

**Comment by viresh-ratnakar** [comment]
And, oh, thanks for the kind remarks, much appreciated!

**Comment by jdacre** [comment]
I've completed two crosswords in the past 2 days and working on another now, such an intuitive and helpful toolkit, wonderful work Viresh!

**Comment by viresh-ratnakar** [comment]
Closing the issue (pls reopen if needed). Also, feel free to share any public links to crosswords that you (anyone!) may have constructed using Exet, on the [Discussions](https://github.com/viresh-ratnakar/exet/discussions) page.
