### ISSUE TITLE
[Feature request] Transadditions / Transdeletions

### ISSUE THREAD

**Issue by mooomooo** [viresh-ratnakar/exet#33]
This'd be another iframe tab (or two) like Hidden / Alternations; with nutrimatic and/or qat queries.  Transadditions are easy, just add another `.` to the query (inside `<>` for nutrimatic or after `/` for qat).  Transdeletions would be harder; you'd have to compose a query of several OR'ed options: with one fewer `.` if any exist, and with one of the entered letters removed for each of the letters.  But that'll open up a bunch of one-letter-off anagram clues.

**Comment by viresh-ratnakar** [comment]
I just pushed Exet v0.93 (changelog pasted below) which should address this, but not quite the way you had requested.

In general, I prefer my own implementations rather than nutrimatic, when possible, to avoid dependencies. For anagrams, Exet already has extensive code that I've now extended.

For what you call "transdeletions": this was already supported and candidates were being shown in the Anagrams tab. I've now added some colouring (single letter components of anagrams are now shown in green) to make it easier to spot them. 

For what you call "transadditions": I have now added what I call "anagrammed deletions" to the charades tab. This is wordplay of the form `*(A - B*)`. See more details below. This includes the case of creating anagrams out of one letter more than the fodder.

As you can see below, I've also taken (A* around B*) out of the charades tab and placed it more prominently in the Charades+Containments tab now.

### Version: Exet v0.93, June 17, 2024

- This version mainly reorganizes the wordplay tabs a bit, adding some
  new functionality.
- Anagram displays now use a common scheme (implemented in
  `ExetLexicon.displayAnagrams()`):
  - Single-letter parts and longer parts that are present intact as
    substrings in the fodder are coloured green.
  - Parts are annotated with `*` (anagram) or `<<` (reversal) or
    nothing, based upon how they appear in the fodder.
  - Enclosing parenthesis are used when needed.
- We add Containments to the Anagrams tab (renaming it as `Anagrams/()`).
  Earlier, containments were buried in the Charades tab, but this
  promotion now recognizes their higher status.
- We add "Anagrammed deletions" to the Charades tab (renaming it
  as `Charades/-`).
  - These are wordplays of the form `*(A - B*)`. This includes the
    special case of forming an anagram with one extra letter than
    the given fodder.
  - Anagrammed deletions are shown together, above charades, in the same
    table. You can easily scroll past them if needed.
  - Anagrammed deletions are implemented using
    `ExetLexicon.getSupersetAnagrams()`. Similar to `getSubsetAnagrams()`,
    this implementaion also uses "salient letter keys" to identify candidates.
  - In charades, we try to not show anagrams/containments that are already
    shown in the `Anagrams/()` tab.
- Add gray border to the Charades/- tab rows, to make them easier to read,
  especially for rows that wrap over.
- Add "press escape to restore" to the Anagrams tab's fodder input area too.
  Simplify the presentation of composite anagrams.

**Comment by mooomooo** [comment]
Ah this is very thorough and does the trick (and more).  Thanks!
