### ISSUE TITLE
More memory managment.

### ISSUE THREAD

**Issue by elwoodpd** [viresh-ratnakar/exet#6]
Would be nice to be able to save revision history as a file (so it can be deleted from local storage and also backed up). It would also be nice to be able to request more local storage space.

**Comment by viresh-ratnakar** [comment]
With v0.31, now there is an option to save revision history as a file, and another to load from such a file, merging the revisions lists (i.e., skipping duplicate ones).

From the README.md file:

### Backing up the revisions stored in local storage

The "Open" menu also has a "Save all revisions to file" option, which saves the
entire revision history to a JSON file (named exet-revisions-_timestamp_.json),
as a way of having a back-up beyond the browser's local storage. Apart from
using as a back-up mechanism, you can also use this to transfer all the
crosswords that you're working on to a different computer. The companion option,
"Merge saved revisions file," lets you read a saved JSON file, merging all
revision state from it. This allows limiting to just the latest version of each
crossword (instead of its full revision history). The revisions are _merged_: in
the sense that if a revision already exists then it is not duplicated.

**Comment by elwoodpd** [comment]
Amazing. Thanks!

**Comment by viresh-ratnakar** [comment]
Closing this, thanks.
