### ISSUE TITLE
[Feature Request] User managed ‘Lists’ resources

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exet#9]
I've been trying out Exet in earnest for the first time – very good I've found it, too! – and while I like the idea of the ‘Lists’ tab, I don't have much use for the resources provided. So I was thinking of asking you to include some of _my_ favourites, but it occurred to me it could become cumbersome for you to maintain a list of user requested sites, and it would force everyone to have the same set, so I thought it might be better if you could make the available sites (in the drop-down list) user editable – i.e. provide methods to add/remove online resources? Is this feasible and would you be interested in implementing it?

**Comment by viresh-ratnakar** [comment]
Certainly feasible! I'm not convinced (yet) that it would be a popular feature -- in the unlikely case that there are a bunch of lurkers listening in, this would be a perfect thing to chime in on!

I'm very interested in learning what _are_ the favourite sites of yours that you would like to add there! I can simply add them directly (unless -- and this is highly unlikely -- there are some in the list that I would not want in there, strongly, for some weird reason). And then we can revisit this feature if it becomes a recurring thing rather than a one-off.

I'm also quite curious as to why you do not find the links that are currently included of much use -- this would be useful info too! I mean, is it the case that you prefer not to browse through lists of indicator words in general, or is it that those specific lists (mostly from crosswordunclued) are inadequate and/or flawed?

BTW, one common look-up that I do while setting is that when I come up with an indicator word that seems slightly unusual, I look up within the fifteensquared site to see if someone has used it before in the way I intend to. I will be adding this as a feature to Exet at some point, I think.

Thanks in advance!

**Comment by Antagony1060** [comment]
Oh I have nothing against the sites you've included – Crossword Unclued is a great resource with articles that I often cite for primers on particular concepts – but yeah, apart from the anagrinds I find their lists to be not comprehensive enough. Take containers: although not separated into contained/containing categories, I like Highlight Press's [page](https://www.highlightpress.com.au/containers.html) for having lots of entries. There is a lot of crossover between ‘in’ or ‘around’ indicators and I actually like that I have to think for myself about whether a particular entry is suitable, or may be adapted, for what I have in mind. I also really like their [subtractions page](https://www.highlightpress.com.au/subtractions.html) which is well organised and has a useful section for removing individual letters.

For abbreviations I do like that the Wikipedia list often explains their origins, but I find the way it's organised – word | abbreviation – to be more useful for solvers than setters. For me, setters need it the other around, so they can find a suitable word for any given letter or letters. That's why I like [this list](https://github.com/mhl/cryptic-crossword-indicators-and-abbreviations/blob/master/indicators.yml), but it doesn't have any explanations and it includes a lot of quite esoteric and/or arcane entries, so I wouldn't necessarily recommend it as a reliable resource. I personally always try to find the justification for any entry I'm not already familiar with, and often end up dismissing them as too obscure. This list in particular is what got me thinking about making the resources user manageable, because it might not be good for beginners, but I'm sure it's helpful for experienced setters.

Oh and I also use [Onelook](https://www.onelook.com) a lot for pattern matching, because I find its filters very useful. I think it's better than most individual dictionary searches too, because its search results include proper names, usually with links to Wikipedia articles. 

That's a good idea re searching FifteenSquared site, you might also want to add the Times for the Times and Big Dave's (Telegraph) sites if/when you implement that.

**Comment by viresh-ratnakar** [comment]
v0.31 adds all the links that you've mentioned, PTAL.

**Comment by Antagony1060** [comment]
That's great, thanks! I still think it would be good to provide management options for the 'Lists' selection at some point, so users can just have an uncluttered set of their personal favourites, but I understand your wish to see more demand for it first.
